apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gr6c8r3o9-python
  janus-idp.io/tekton: gr6c8r3o9-python
  backstage.io/kubernetes-id: gr6c8r3o9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gr6c8r3o9-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
