apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gr6c8r3o9-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gr6c8r3o9-python 
  name: gr6c8r3o9-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gr6c8r3o9-python 
